import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeScreen from './src/HomeScreen'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>TL1</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <HomeScreen />
    </>
  )
}
